### ISSUE TITLE
ok_proj6() always return FALSE. why to design it ?

### ISSUE THREAD

**Issue by bigdataman2015** [hypertidy/PROJ#31]
ok_proj6() always return FALSE. why to design it ?

```
>PROJ::ok_proj6
function ()
{
FALSE
}
<bytecode: 0x00000197f0ec1cf8>
<environment: namespace:PROJ>
```

**Comment by mdsumner** [comment]
The package is currently non functional sadly, I had to lock it down to stay safe on cran and allow {reproj} to function. Once {libproj} gets on cran I'll standardize on that 🙏

**Comment by mdsumner** [comment]
this will be fixed soon
