### ISSUE TITLE
replace proj_trans with wk::xy impl.

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/PROJ#49]

**Comment by mdsumner** [comment]
@anthonynorth one thing I just don't understand atm is why the calls to `P = proj_create_crs_to_crs(C, *crs_in, *crs_out, NULL);` accept a string like "+proj=laea" now in C_proj_trans.c, but the same calls in wk-trans.c and C_proj_crs_text.c do not. 

i. e

```R
proj_trans(0, 0, "+proj=laea +lon_0=147", source = "OGC:CRS84")
#$x_
#[1] -12230967
#$y_
# [1] 0


proj_crs_text("+proj=laea") 
##[1] "CONVERSION[\"PROJ-based coordinate operation\",\n    METHOD[\"PROJ-based operation method: +proj=laea\"]]" 
  |  
 

proj_trans_create("OGC:CRS84", "+proj=laea")
Error in proj_trans_create("OGC:CRS84", "+proj=laea") : 
  Unknown error (code 4096)
proj_create_operations: target_crs is not a CRS or a CoordinateMetadata


```

Like, why does proj_trans work now?    It works with the correct addition of `+type=crs` and now is probably a good time to apply that as a requirement (we could help a user with warnings). 

```R
proj_crs_text("+proj=laea +type=crs") 
 
proj_trans_create("OGC:CRS84", "+proj=laea +type=crs")

```

I'll proceed with that for now, but  it leaves me wondering why it's working now in proj_trans ...

PROJ::proj_version()
[1] "9.3.1"

**Comment by mdsumner** [comment]
here's a rough benchmark for reference (is this the kind of difference you were seeing?)

``` r
library(PROJ)

dummy <- local({ 
  proj_trans_create("OGC:CRS84", "+proj=laea +type=crs")
  proj_trans(cbind(0, 0), "OGC:CRS84", source = "+proj=laea +type=crs +lon_0=147")
})
xyn <- geosphere::randomCoordinates(1e7)
system.time(proj_trans(xyn, "+proj=laea", source = "OGC:CRS84"))
#>    user  system elapsed 
#>   3.424   0.303   3.727

xyn <- geosphere::randomCoordinates(1e7)
xy <- wk::xy(xyn[,1], xyn[,2], crs = "OGC:CRS84")
trans <- proj_trans_create("OGC:CRS84", "+proj=laea +type=crs")
system.time(pp <- wk::wk_transform(xy, trans))
#>    user  system elapsed 
#>   4.183   0.099   4.283

xyn <- geosphere::randomCoordinates(1e7)
system.time({
xy <- wk::xy(xyn[,1], xyn[,2], crs = "OGC:CRS84")
trans <- proj_trans_create("OGC:CRS84", "+proj=laea +type=crs")
pp <- wk::wk_coords(wk::wk_transform(xy, trans))[,c("x", "y")]
})
#>    user  system elapsed 
#>   4.118   0.400   4.518
```

<sup>Created on 2024-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mdsumner** [comment]
- [x] replace proj_trans with wk version
- [ ] replace all PROJ.4 strings with "+type=crs" included
- [ ] test for bad input without "type=crs"
- [ ]  test other bad inputs (this can be pretty liberal strings like "4326" and "NAD27" that currently crash PROJ (yikes))
- [ ] pass tests and read doc for sense ....

**Comment by anthonynorth** [comment]
Ok, tracked down the cause. Tracking in #52
