### ISSUE TITLE
failing in 32-bit windows

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/PROJ#7]
In branch [no-onload](https://github.com/hypertidy/PROJ/tree/no-onload), the build fails in 32-bit mode as seen on Appveyor. 

(The .onLoad test that sets an option is disabled, so the package compiles and installs). 

If I start 32-bit R and run this it works, without the `Sys.setenv()` it fails (it's fine in 64-bit). 

Is there something about how the different architectures treat the "working directory"? 

```R
Sys.setenv(PROJ_LIB= system.file("proj", package = "PROJ"))
library(PROJ)
proj_trans_generic(cbind(147, -42), "+proj=laea", source = "epsg:4326")
```

The PROJ FAQ describes how the file `proj.db` is found: https://github.com/OSGeo/PROJ/blob/e151e92371772c5bad5001f94f79618ca192eb5d/docs/source/faq.rst#why-am-i-getting-the-error-cannot-find-projdb

Any ideas?  @jeroen

**Comment by jeroen** [comment]
I think you should NOT use PROJ_LIB variable with proj6 because other packages will use this for proj4 data. See here: https://github.com/r-spatial/sf/issues/1074

**Comment by mdsumner** [comment]
Oh ok, I wasn't suggesting it as a solution though

**Comment by mdsumner** [comment]
Looks like that will solve it though, using the API - thanks again

**Comment by mdsumner** [comment]
done, thanks heaps! 


https://github.com/hypertidy/PROJ/commit/01caa852ad498879dc670335b04ff0dc3e70a43f
